### ISSUE TITLE
Client crashes when Soul Lily Sapling tries to grow- 

### ISSUE THREAD

**Issue by the-ecips** [quiqueck/BetterNether#21] opened 2022-06-20 08:21 UTC
**What happened?**
Tested multiple times on different maps:
- Plant Soul Lily Sapling in the Overworld on a block of Soul Sand
- Game randomly crashes (I believe as soon as the Soul Lily tries to grow)

Edit:
Crashes without Error Log when growing Soul Lily Saplings in the Nether.

**BetterNether**
7.0.2

**BCLib**
2.0.5

**Fabric API**
0.56.0

**Fabric Loader**
0.14.8

**Minecraft**
1.19

**Relevant log output**
Client Error msg:
The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "this.plant" is null
Exit-Code: -1

Crash Report:
Time: 20.06.22, 10:03
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "this.plant" is null
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9652(BlockCommonSapling.java:97)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9652(BlockSoulLilySapling.java:11)
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9588(BlockCommonSapling.java:104)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9588(BlockSoulLilySapling.java:11)
	at net.minecraft.class_4970.method_9514(class_4970.java:366)
	at net.minecraft.class_2248.method_9514(class_2248.java:2675)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947)
	at net.minecraft.class_3218.redirect$cjg000$redirectBlockStateTick(class_3218.java:7731)
	at net.minecraft.class_3218.method_18203(class_3218.java:495)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Other Mods**
`See attached Crashlog`
[crash-2022-06-20_10.03.08-server.txt](https://github.com/quiqueck/BetterNether/files/8938858/crash-2022-06-20_10.03.08-server.txt)

**Comment by Nekoli** [comment] 2022-06-23 00:01
Same issue.
[crash-2022-06-22_23.13.18-server.txt](https://github.com/quiqueck/BetterNether/files/8962539/crash-2022-06-22_23.13.18-server.txt)

**Comment by quiqueck** [comment] 2022-06-24 23:30
Duplicate of #8

**Closed as completed by quiqueck** 2022-06-24 23:30 UTC
Labels: 🥈 duplicate

**Comment by the-ecips** [comment] 2022-06-30 09:28
Since it's marked as duplicate, does that mean that all the plants from the betternether can crash the game? I'm just curious, since I haven't had problems with the black apple seeds that are mentioned in #8  :)

**Comment by quiqueck** [comment] 2022-06-30 23:08
Not all of them, but a select few :) Anyway it should be fixed in 7.0.4
