### ISSUE TITLE
[Bug] Quartz doesn't seem to spawn...?

### ISSUE THREAD

**Issue by Haihatu** [quiqueck/BetterNether#40] opened 2022-07-20 23:28 UTC
### What happened?

When playing on the latest release of BetterNether 1.19 for Fabric, quartz doesnt seem to spawn...? 
I keep seeing holes while mining thinking they were small caves but I could not find a single bit of (normal) quartz, making me believe the mod messed up with their generation and just not generate anymore. I could only find one bit of quartz using the universal ores mod but there seems to be no quartz otherwise whatsoever. 

### BetterNether

7.0.6

### BCLib

2.0.16

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment] 2022-07-21 08:53
Could you please provide your logs and a list of other Mods. This (as of yet) is not a known problem, so it probably is a conflict with another mod.

BetterNether itself does not change the way Quartz is placed.

**Comment by SammySame** [comment] 2022-07-24 12:12
I have the same problem, but the reason is the mod "**Universal Ores**".
Here is the bug report, with the same problem in [this](https://github.com/DawnTeamMC/UniversalOres/issues/21) thread.
The author of the mod confirmed that it is indeed an error he made and the fix will be available in next patch.

Hope it helps!

**Comment by quiqueck** [comment] 2022-07-25 05:39
Thanks for reporting. I'll close this on our end then :)

**Closed as completed by quiqueck** 2022-07-25 05:39 UTC
Labels: 💡 question
