### ISSUE TITLE
[Bug] You can see through any block with a fully grown ink bush on it.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [quiqueck/BetterNether#130] opened 2023-04-30 01:01 UTC
### What happened?

As the title states.

Image:
![image](https://user-images.githubusercontent.com/60951301/235330431-81584c38-8a85-40d9-a545-63949aae99ec.png)

Log:
[latest.log](https://github.com/quiqueck/BetterNether/files/11360370/latest.log)

Mod list:
![Untitled](https://user-images.githubusercontent.com/60951301/235330503-58b42068-8a04-4e0f-b2e9-4764d5c30d34.png)

### BetterNether

7.1.3

### BCLib

2.1.6

### Fabric API

0.76.0

### Fabric Loader

0.14.19

### Minecraft

1.19.2

**Comment by TrueDevron** [comment] 2023-05-06 23:54
Also having this issue, same FAPI, loader, library and mod versions.

**Comment by MMDGLaDOS** [comment] 2023-05-20 16:53
Same we have more mods as well and we have the sme issue for that and the firebowls

**Comment by MMDGLaDOS** [comment] 2023-05-31 19:39
> ### What happened?
> 
> As the title states.
> 
> Image: ![image](https://user-images.githubusercontent.com/60951301/235330431-81584c38-8a85-40d9-a545-63949aae99ec.png)
> 
> Log: [latest.log](https://github.com/quiqueck/BetterNether/files/11360370/latest.log)
> 
> Mod list: ![Untitled](https://user-images.githubusercontent.com/60951301/235330503-58b42068-8a04-4e0f-b2e9-4764d5c30d34.png)
> ### BetterNether
> 
> 7.1.3
> ### BCLib
> 
> 2.1.6
> ### Fabric API
> 
> 0.76.0
> ### Fabric Loader
> 
> 0.14.19
> ### Minecraft
> 
> 1.19.2
> ### Relevant log output
> 
> _No response_
> ### Other Mods
> 
> _No response_

I figured out what it was its More-Culling if you go into its configs and disable mod compatibility for BetterNether this issue completely stops i was having the same issue in a SMP modpack me and a friend were designing for a while now and its was being delayed soo long till we realized it was a Block Culling thing. I hope this helps!

**Comment by quiqueck** [comment] 2023-06-14 07:34
Duplicate of #137.  I contacted the Author of MoreCulling to find a solution.

**Closed as completed by quiqueck** 2023-06-14 07:34 UTC
Labels: 🥈 duplicate
