### ISSUE TITLE
Crash on Game boot

### ISSUE THREAD

**Issue by KitsuneDevSys** [quiqueck/BetterNether#47] opened 2022-08-16 21:20 UTC
### What happened?

Game crashes on boot with only the required mods.
Minecraft version 1.19.2.
When I remove main menu credits (from fabulously optimized mod pack)I then crash due to midnight controllers; however, if I just remove betternether and keep bclib and all my previous mods on my main installation the game doesn't crash.

### BetterNether

7.0.9

### BCLib

2.0.20

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Relevant log output

```shell
Installation with only required mods:

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.build(SpawnRuleBuilder.java:316)
	at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.buildNoRestrictions(SpawnRuleBuilder.java:325)
	at org.betterx.betternether.registry.NetherEntities.register(NetherEntities.java:289)
	at org.betterx.betternether.BetterNether.onInitialize(BetterNether.java:38)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more


Main installation:

java.lang.NullPointerException: Cannot invoke "dev.isxander.mainmenucredits.MainMenuCredits.getConfig()" because the return value of "dev.isxander.mainmenucredits.MainMenuCredits.getInstance()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.4)
	at net.minecraft.client.gui.screen.TitleScreen.handler$dan001$addText(TitleScreen:1022)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen:157)
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:389)
	at net.minecraft.client.gui.screen.Screen.init(Screen:380)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1035)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:668)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Other Mods

```shell
Installation with only required mods:
None

Main Installation:
advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		animatica: Animatica 0.5+1.19
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		architectury: Architectury 6.2.43
		bclib: BCLib 2.0.20
		bettermounthud: Better Mount HUD 1.1.4
		betternether: Better Nether 7.0.9
		borderlessmining: Borderless Mining 1.1.5+1.19
		byg: Oh The Biomes You'll Go 2.0.0.7
		capes: Capes 1.4.4+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		colormatic: Colormatic 3.1.2+mc.1.19
		continuity: Continuity 2.0.1+1.19
		cull-less-leaves: Cull Less Leaves 1.0.4
			conditional-mixin: conditional mixin 0.3.0
		debugify: Debugify 2.4.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		dehydration: Dehydration 1.2.9
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enchantinginfuser: Enchanting Infuser 4.1.1
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entity_texture_features: Entity Texture Features 4.0.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		environmentz: EnvironmentZ 1.2.3
fabrishot: Fabrishot 1.8.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.1.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		holdthatchunk: Hold That Chunk 1.0.3
		immersive_portals: Immersive Portals 2.2.0
			imm_ptl_core: Immersive Portals Core 2.2.0
			q_misc_util: QMiscUtil 2.2.0
		indium: Indium 1.0.7+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		languagereload: Language Reload 1.3.1
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.3
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightcontrols: MidnightControls 1.5.0+1.19
			midnightlib: MidnightLib 0.5.2
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.1.0
		modmenu: Mod Menu 4.0.6
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.19.1-0.9.1
			cloth-config: Cloth Config v6 7.0.74
				cloth-basic-math: cloth-basic-math 0.6.1
		mousetweaks: Mouse Tweaks 2.22
		nochatreports: No Chat Reports 1.19.2-v1.9.1
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		numismatic-overhaul: Numismatic Overhaul 0.2.3+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			stacc: Stacc 1.3.3
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.7.3+1.19
		puzzle: Puzzle 1.4.0-1.19
			puzzle-base: Puzzle Base 1.4.0-1.19
			puzzle-gui: Puzzle GUI 1.4.0-1.19
			puzzle-models: Puzzle Models 1.4.0-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.19
		puzzleslib: Puzzles Lib 4.1.6
		reborncore: Reborn Core 5.3.3
			team_reborn_energy: Energy 2.2.0
		reeses-sodium-options: Reese's Sodium Options 1.4.5+mc1.19.2-build.51
		roughlyenoughitems: Roughly Enough Items 9.1.528
			error_notifier: Error Notifier 1.0.9
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		techreborn: Tech Reborn 5.3.3
		terrablender: TerraBlender 2.0.1.125
		tooltipfix: ToolTip Fix 1.0.5-1.19
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		yosbr: YOSBR 0.1.1
		zoomify: Zoomify 2.0.3
			dev_isxander_settxi_settxi-core: settxi-core 2.5.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.5.3
			settxi-gui-cloth-config: Settxi Gui (Cloth Config) 2.5.3
```

**Comment by quiqueck** [comment] 2022-08-17 01:28
Duplicate of quiqueck/BCLib#33

**Closed as completed by quiqueck** 2022-08-17 01:28 UTC
