### ISSUE TITLE
[Bug] Structures can generate in the city

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#28] opened 2022-06-30 11:43 UTC
### What happened?

Sometimes biomes structures can be generated inside city

![2022-06-30_14 26 10](https://user-images.githubusercontent.com/17707380/176668830-3d9d3eb9-d828-46a0-bf33-04ebf34e5c6c.png)

### BetterNether

7.0.3

### BCLib

2.0.6

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
better-end-2.0.3
eden-ring-0.6.3
enderscape-0.3.0
geckolib-fabric-1.19-3.1.2
iris-mc1.19-1.2.5
mantori-1.1.0-1.19
modmenu-4.0.0
sodium-fabric-mc1.19-0.4.2+build.16
worldedit-mod-7.2.11-beta-01
```

**Comment by quiqueck** [comment] 2022-06-30 12:55
duplicate of #19

**Closed as completed by quiqueck** 2022-06-30 12:55 UTC
