### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dalekfan** [quiqueck/BetterNether#22] opened 2022-06-21 01:21 UTC
### What happened?

So I'm trying to grow soul lily saplings, and for some reason, they won't grow no matter how much bonemeal I feed them. Not only that, but I got a crash trying to grow them in the overworld!
[crash-2022-06-20_21.01.00-server.txt](https://github.com/quiqueck/BetterNether/files/8944923/crash-2022-06-20_21.01.00-server.txt)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 6/20/22, 9:01 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "this.plant" is null
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9652(BlockCommonSapling.java:97)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9652(BlockSoulLilySapling.java:11)
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9588(BlockCommonSapling.java:104)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9588(BlockSoulLilySapling.java:11)
	at net.minecraft.class_4970.method_9514(class_4970.java:366)
	at net.minecraft.class_2248.method_9514(class_2248.java:2175)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947)
	at net.minecraft.class_3218.method_18203(class_3218.java:495)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9652(BlockCommonSapling.java:97)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9652(BlockSoulLilySapling.java:11)
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9588(BlockCommonSapling.java:104)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9588(BlockSoulLilySapling.java:11)
	at net.minecraft.class_4970.method_9514(class_4970.java:366)
	at net.minecraft.class_2248.method_9514(class_2248.java:2175)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947)
	at net.minecraft.class_3218.method_18203(class_3218.java:495)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
```

### Other Mods

```shell
Blossom, capsey archeology, charm, ydm's allay, 3d skins, collective, colorful goats, betterend, dramatic doors, dualwielding, crying ghasts, spiders make cobwebs, dyeable shulkers, hauling hog, greatereye, guard villagers, herds panic, illuminations, architectury, appleskin, advanced netherrite, beacon overhaul, broken nametags, cauldron dyeing, badpackets, rei, your reputation, adventurez, charmonium, cloth config, cleardespawn, dimensioncoordconverter, dynamic fps, earthtojavamobs, effective, froglegs, fastload, kotlin, geckolib, hwyla horseinfo, nyfs quiver, npc variety, more leads, more geodes, immersive weathering, indypets, milkplus, mcf easyfeed, missingwilds, llamasteeds, mobs attempt parkour, modmenu, more babies, respawnable pets, sheepconsistency, sleepwarp, snowyleavesplus, sodium, enhanced spawnermod, spyglasszoom, stb, strawgolem, trinkets, unvoted shelved, vanity slots, villager hats, visuality wmitaf, wooled boots, wraith musica, wthit, wunderreich, xaeros minimap
```

**Comment by the-ecips** [comment] 2022-06-22 09:08
Already opened this issue 2 days ago, kinda "glad" to see that I'm not the only one with this issue.
See https://github.com/quiqueck/BetterNether/issues/21  :)

**Comment by quiqueck** [comment] 2022-06-24 23:27
Duplicate of #21

**Closed as completed by quiqueck** 2022-06-24 23:27 UTC
Labels: 🥈 duplicate
